  workflowdoc2: 
    build: 
         .     
    environment: 
        - RUN_MODE=docker
        - MONGO_HOST=mongo
    ports: 
        - "9002:8080"
    links:
        - "mongodb"

  mongodb: 
    image: mongo
    volumes:  
         - /OSM/MEL/LW_OZNOME/workflowdoc/mongodb-data:/data/db
    command: --smallfiles --rest 
