version: '1'

volumes:
    hello:
        driver: local

services:
  workflowdoc:
    build:
        dockerfile: Dockerfile
    volumes:
        - /srv/workflowdoc/src: /projects/workflowdoc/src 
    environment:
        - RUN_MODE=docker
        - MONGO_HOST=mongo
    ports:
        3000:3000
    depends_on:
        - mongodb

  mongodb:
    image: mongo
    EXPOSE: 27017
    volumes:
          /OSM/MEL/LW_OZNOME/workflowdoc/mongodb-data: /data/db #makes sure any data is persisted on machine between container up/downs.