  workflowdoc:
    build:
         .     
    volumes:
        - /srv/workflowdoc:/usr/src/app
   environment:
        - RUN_MODE=docker
        - MONGO_HOST=mongo
    ports:
        - "8080:8080"

  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
         - /OSM/MEL/LW_OZNOME/workflowdoc/mongodb-data:/data/db
    command: --smallfiles --rest --auth
