version: '2'

volumes:
    hello:
        driver: local

services:
  workflowdoc:
    build:
        dockerfile: Dockerfile
    volumes:
        - /srv/workflowdoc/src:/projects/workflowdoc/src 
    environment:
        - RUN_MODE=docker
        - MONGO_HOST=mongo
    ports:
        - 3000:3000
    depends_on:
        - mongodb

  mongodb:
    image: mongo
    expose:
         - 27017
    volumes:
         - /OSM/MEL/LW_OZNOME/workflowdoc/mongodb-data:/data/db